export const FEATURED_UNIVERSITIES = [
  {
    id: "univ_001",
    name: "Harvard University",
    location: "Cambridge, MA, USA",
    ranking: 1,
    rating: 4.9,
    students: 23000,
    acceptanceRate: 3.4,
    image: "/harvard-university.jpg",
    logo: "/harvard-logo.png",
    description:
      "Oldest institution of higher education in the United States, renowned for academic excellence across all disciplines",
    established: 1636,
    type: "Private",
    tuitionRange: "$54,000 - $58,000",
    popularPrograms: ["Business", "Medicine", "Law", "Computer Science"],
    strengths: [
      "Research Excellence",
      "Alumni Network",
      "Financial Aid",
      "Global Recognition",
    ],
  },
  {
    id: "univ_002",
    name: "Stanford University",
    location: "Stanford, CA, USA",
    ranking: 2,
    rating: 4.8,
    students: 17000,
    acceptanceRate: 4.3,
    image: "/stanford-university-campus.png",
    logo: "/stanford-university-logo.png",
    description:
      "Leading research university known for innovation, entrepreneurship, and Silicon Valley connections",
    established: 1885,
    type: "Private",
    tuitionRange: "$58,000 - $62,000",
    popularPrograms: [
      "Computer Science",
      "Engineering",
      "Business",
      "Medicine",
    ],
    strengths: [
      "Innovation Hub",
      "Entrepreneurship",
      "Tech Industry Connections",
      "Research Funding",
    ],
  },
  {
    id: "univ_003",
    name: "MIT",
    location: "Cambridge, MA, USA",
    ranking: 3,
    rating: 4.8,
    students: 11500,
    acceptanceRate: 6.7,
    image: "/mit-campus.jpg",
    logo: "/mit-logo-generic.png",
    description:
      "Massachusetts Institute of Technology - Premier institution for science, technology, engineering, and mathematics",
    established: 1861,
    type: "Private",
    tuitionRange: "$57,000 - $61,000",
    popularPrograms: [
      "Engineering",
      "Computer Science",
      "Physics",
      "Economics",
    ],
    strengths: [
      "STEM Excellence",
      "Research Innovation",
      "Industry Partnerships",
      "Nobel Laureates",
    ],
  },
  {
    id: "univ_009",
    name: "University of Oxford",
    location: "Oxford, England, UK",
    ranking: 4,
    rating: 4.7,
    students: 24000,
    acceptanceRate: 17.5,
    image: "/oxford-university.jpg",
    logo: "/oxford-logo.png",
    description:
      "Oldest university in the English-speaking world, renowned for academic excellence and tradition",
    established: 1096,
    type: "Public",
    tuitionRange: "$12,000 - $15,000",
    popularPrograms: ["PPE", "Medicine", "Law", "Literature"],
    strengths: [
      "Academic Tradition",
      "Tutorial System",
      "Global Alumni",
      "Research Excellence",
    ],
  },
  {
    id: "univ_010",
    name: "University of Cambridge",
    location: "Cambridge, England, UK",
    ranking: 5,
    rating: 4.7,
    students: 23000,
    acceptanceRate: 21.0,
    image: "/cambridge-university.jpg",
    logo: "/cambridge-logo.png",
    description:
      "Historic university known for scientific research and distinguished alumni including Newton and Hawking",
    established: 1209,
    type: "Public",
    tuitionRange: "$12,000 - $15,000",
    popularPrograms: [
      "Natural Sciences",
      "Medicine",
      "Engineering",
      "Mathematics",
    ],
    strengths: [
      "Scientific Research",
      "Nobel Prize Winners",
      "Collegiate System",
      "Academic Excellence",
    ],
  },
  {
    id: "univ_017",
    name: "ETH Zurich",
    location: "Zurich, Switzerland",
    ranking: 8,
    rating: 4.6,
    students: 22000,
    acceptanceRate: 27.0,
    image: "/eth-zurich.jpg",
    logo: "/eth-logo.png",
    description:
      "Swiss Federal Institute of Technology known for science, technology, engineering, and mathematics",
    established: 1855,
    type: "Public",
    tuitionRange: "$1,500 - $2,500",
    popularPrograms: [
      "Engineering",
      "Computer Science",
      "Physics",
      "Mathematics",
    ],
    strengths: [
      "Affordable Excellence",
      "Research Quality",
      "Industry Connections",
      "International Environment",
    ],
  },
];

export const UNIVERSITY_STATS = {
  totalUniversities: 20,
  totalStudents: 450000,
  countriesRepresented: 12,
  averageRating: 4.6,
  topRankedPrograms: 150,
};

export const POPULAR_SEARCHES = [
  "Computer Science programs",
  "Medical schools",
  "Business schools",
  "Engineering programs",
  "Affordable universities",
  "Ivy League schools",
  "UK universities",
  "Scholarship opportunities",
];
